[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'

[tool.vulture]
min_confidence = 70
sort_by_size = true

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
indent='    '
sections = ['FUTURE','STDLIB','THIRDPARTY','FIRSTPARTY','LOCALPROJECT','LOCALFOLDER']
default_section = 'THIRDPARTY'
known_standard_library = []
known_localproject = ['starlette_i18n','tests']